name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material

      - name: Build site
        run: mkdocs build

      - name: Deploy to gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Clone or init gh-pages
          if git ls-remote --exit-code --heads https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} gh-pages; then
            git clone --branch gh-pages https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} gh-pages
          else
            git clone https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} gh-pages
            cd gh-pages
            git checkout --orphan gh-pages
            cd ..
          fi

          rm -rf gh-pages/*
          cp -r site/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Deploy MkDocs site"
          git push origin gh-pages --force
